Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,15 +17,23 @@ jobs:
       - name: Generate GitHub contribution grid snake
         uses: Platane/snk/svg-only@v3
         with:
-          github_user_name: ${{ github.repository_owner }} # Substitua se necessário
-          palette: github-dark # Personalize a paleta de cores
-        outputs: 
-          svg-path: dist/github-contribution-grid-snake.svg
-           
+          github_user_name: ${{ github.repository_owner }}
+          palette: github-dark
+        id: generate-snake
+
+      - name: Check if snake SVG was generated
+        run: |
+          if [ -f dist/github-contribution-grid-snake.svg ]; then
+            echo "Snake SVG generated successfully"
+          else
+            echo "Failed to generate snake SVG. Exiting workflow."
+            exit 1
+          fi
+
       - name: Push snake animation to output branch
         uses: crazy-max/ghaction-github-pages@v3.1.0
         with:
-          target_branch: gh-pages # Substitua pelo nome da sua branch de saída
+          target_branch: gh-pages
           build_dir: dist
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
